### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by qtbrin** [Icesofty/1hour#13]
Chrome Version: 87.0.4280.66
![1hour-error](https://user-images.githubusercontent.com/75215560/100550503-9a3cb200-327a-11eb-82df-85e2f3c65a79.PNG)

**Comment by Icesofty** [comment]
On it

**Comment by Icesofty** [comment]
Fixed in https://github.com/Icesofty/1hour/commit/7e29e12fae59c4ff0b1b16c2b5364c3acd5c3fde 
Waiting for your PR before Merging into main
