### ISSUE TITLE
Improve input submission

### ISSUE THREAD

**Issue by nterol** [Icesofty/1hour#26]
Empty input should not be valid 
There should not be multiple occurrences of the same websites. 
<img width="241" alt="Capture d’écran 2020-12-07 à 18 18 30" src="https://user-images.githubusercontent.com/24438131/101382992-e14d2780-38b8-11eb-9305-a1cc7403011b.png">

**Comment by Icesofty** [comment]
I'll wait until 10 dec. If nobody takes this issue, I will. Thanks @nterol

**Comment by BlandineRoustan** [comment]
I would like to take this one (I'm done in fact...). Can I change the code directly on dev branch and PR ?
@arthureichelberger

**Comment by arthurdotwork** [comment]
Hi! 

You need to fork the repository, create a branch from develop, make your updates on it, push, and finally create a pull request.
The process is well described [here](https://www.youtube.com/watch?v=nT8KGYVurIU). Don't hesitate to ask if you have any questions!
