### ISSUE TITLE
Add time to Local Storage

### ISSUE THREAD

**Issue by Icesofty** [Icesofty/1hour#3]

**Comment by arthureichelberger** [comment]
Hello Florian, je prends si ça ne te dérange pas.

**Comment by Icesofty** [comment]
> Hello Florian, I'll take if you don't mind.

Sure

**Comment by arthureichelberger** [comment]
Hello Florian,

Here is the **[Pull Request](https://github.com/Icesofty/1hour/pull/5)** for the resolution of **[ticket 3](https://github.com/Icesofty/1hour/issues/3)**.

First, I created a helper that abstracts the callback notions of Chrome Storage by turning them into Promise. I then modified the background.js code to fit this need, and I refactorized some background code elements.

I had to slightly touch the popup code to allow the storage of time in the Chrome Storage.

Do you want me to refactor the popup.js to use the Storage abstraction, or do you want us to do it in the next Pull Request?

Keep me informed and don't hesitate if you see any problem.

_PS: Maybe you would like to do some pair programming to review this? Let me know._

**Comment by Icesofty** [comment]
Fixed with #5
