### ISSUE TITLE
Once time exceeds one hour, the timer is no longer reset to 0 each day.

### ISSUE THREAD

**Issue by arthureichelberger** [Icesofty/1hour#8]
Hi! 👋🏻

As the title explains it rather well, the timer would have to be **reset each day to initiate a new procrastination time.**

This issue is a **good first issue** for beginners.

In my opinion, we should add a key in the Chrome Storage that defines the last date (DD-MM-YYYYY) at which the timer was reset. If this key doesn't exist in the Storage, then it should be created and initialized to the current date.

If it exists and we are not on the same date as the one entered in the Storage, then we must update this key and reset the timer.

Let me know if you want to take this issue and if you would like to solve it in pair programming. 🤓

**Comment by Icesofty** [comment]
Anyone? 
If nobody takes this issue, we can in pair programming.

**Comment by Elya29** [comment]
I'm on it 👍

**Comment by Elya29** [comment]
Fixed here https://github.com/Icesofty/1hour/pull/17
